language: python
python: 3.6
os: linux
dist: focal

script: make build

deploy:
  provider: releases
  token: ${GITHUB_TOKEN}
  edge: true
  on: {tags: true}

jobs:
  include:
  - os: linux
    dist: bionic
    addons: {apt: {packages: [python3-pip, python3-setuptools]}}
    install:
    - gem install --no-document fpm
    before_deploy:
    - mv target/ntuoc13-punch-clock.deb
         target/ntuoc13-punch-clock-bionic.deb
    deploy:
      file: target/ntuoc13-punch-clock-bionic.deb
  - os: linux
    dist: focal
    addons: {apt: {packages: [python3-pip, python3-setuptools]}}
    install:
    - gem install --no-document fpm
    before_deploy:
    - mv target/ntuoc13-punch-clock.deb
         target/ntuoc13-punch-clock-focal.deb
    deploy:
      file: target/ntuoc13-punch-clock-focal.deb
  - os: windows
    language: shell
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    install:
    - choco install make nsis vcredist2010 vcredist2012 vcredist2015
    - choco install python3 --version=3.6.8
    before_deploy:
    - mv target/ntuoc13-punch-clockSetup.exe
         target/ntuoc13-punch-clock-installer.exe
    deploy:
      file: target/ntuoc13-punch-clock-installer.exe
