language: python
python: 3.6
os: linux

install: pip3 install -r requirements/base.txt
script: make build

jobs:
  include:
  - os: linux
    addons: {apt: {packages: [python3-pip, python3-setuptools]}}
    before_install:
    - gem install --no-document fpm
    - python -m venv env
    - source env/bin/activate
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file: target/ntuoc13-check-in-machine.deb
      edge: true
      on: {tags: true}
  - os: windows
    language: shell
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    before_install:
    - choco install make nsis vcredist2010 vcredist2012 vcredist2015
    - choco install python3 --version=3.6.8
    - python -m venv env
    - source env/Scripts/activate
    after_success:
    - mv target/ntuoc13-check-in-machineSetup.exe
         target/ntuoc13-check-in-machine-installer.exe
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file: target/ntuoc13-check-in-machine-installer.exe
      edge: true
      on: {tags: true}
