language: python
python: 3.6
os: linux
dist: focal

install: pip3 install -r requirements/base.txt
script: make build

jobs:
  include:
  - os: linux
    addons: {apt: {packages: [python3-pip, python3-setuptools]}}
    before_install:
    - gem install --no-document fpm
    deploy:
      provider: releases
      token: ${GITHUB_TOKEN}
      file: target/ntuoc13-punch-clock.deb
      edge: true
      on: {tags: true}
  - os: windows
    language: shell
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    before_install:
    - choco install make nsis vcredist2010 vcredist2012 vcredist2015
    - choco install python3 --version=3.6.8
    after_success:
    - mv target/ntuoc13-punch-clockSetup.exe
         target/ntuoc13-punch-clock-installer.exe
    deploy:
      provider: releases
      token: ${GITHUB_TOKEN}
      file: target/ntuoc13-punch-clock-installer.exe
      edge: true
      on: {tags: true}
